#
# Copyright (c) 2022-2023 SMALLPROGRAM <https://github.com/smallprogram/OpenWrtAction>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/smallprogram/OpenWrtAction
# Description: Build OpenWrt using GitHub Actions
#

name: Build-OpenWrtSelfHost

on:
  repository_dispatch:
    types: [openwrt_source_update]
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
      is_display_detailed:
        description: 'Whether to display detailed information about compilation'
        required: false
        default: 'false'
      is_single_threaded:
        description: 'Whether single-threaded compilation'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds_config/lean.feeds.conf.default
  CONFIGS: config/leanlede_config
  DIY_P1_SH: diy_script/lean_diy/diy-part1.sh
  DIY_P2_SH: diy_script/lean_diy/diy-part2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_ARTIFACT: false
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai



jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@main
  
    
    # - name: Update Action Source
    #   id: UpdateSource
    #   run: |
    #     cd /home/$USER/actions-runner/_work/OpenWrtAction/OpenWrtAction
    #     bash SelfHostCheck.sh
    #     echo "status=success" >> $GITHUB_OUTPUT

    # - name: Compile the firmware
    #   id: compile
    #   if: steps.UpdateSource.outputs.status == 'success' && !cancelled()
    #   run: |
    #     cd /home/$USER/OpenWrtAction
    #     # bash wsl2op.sh $CONFIG_NAME
    #     echo "status=error" >> $GITHUB_OUTPUT
    #     cd /home/$USER/lede_$CONFIG_NAME
    #     grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
    #     [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
    #     echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV