#
# Copyright (c) 2022-2023 SMALLPROGRAM <https://github.com/smallprogram/OpenWrtAction>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/smallprogram/OpenWrtAction
# Description: Build OpenWrt using GitHub Actions
#

name: Build-OpenWrt_SelfHost_All

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  # schedule:
  #   - cron: 0 */8 * * *

env:
  TZ: Asia/Shanghai


jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@main
  
    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
    
    - name: Update Action Source
      id: UpdateSource
      run: |
        cd /home/$USER/actions-runner/_work/OpenWrtAction/OpenWrtAction
        bash SelfHostCheck.sh
        echo "::set-output name=status::success"

    - name: Compile the firmware X64
      id: compile_X64
      if: steps.UpdateSource.outputs.status == 'success' && !cancelled()
      run: |
        cd /home/$USER/OpenWrtAction
        bash wsl2op.sh x64.config
        echo "::set-output name=status::success"
    
    - name: Compile the firmware R5S
      id: compile_R5S
      if: steps.UpdateSource.outputs.status == 'success' && !cancelled()
      run: |
        cd /home/$USER/OpenWrtAction
        bash wsl2op.sh R5S.config
        echo "::set-output name=status::success"

    - name: Compile the firmware R4S
      id: compile_R4S
      if: steps.UpdateSource.outputs.status == 'success' && !cancelled()
      run: |
        cd /home/$USER/OpenWrtAction
        bash wsl2op.sh R4S.config
        echo "::set-output name=status::success"

    - name: Compile the firmware R2S
      id: compile_R2S
      if: steps.UpdateSource.outputs.status == 'success' && !cancelled()
      run: |
        cd /home/$USER/OpenWrtAction
        bash wsl2op.sh R2S.config
        echo "::set-output name=status::success"

    - name: Compile the firmware R2C
      id: compile_R2C
      if: steps.UpdateSource.outputs.status == 'success' && !cancelled()
      run: |
        cd /home/$USER/OpenWrtAction
        bash wsl2op.sh R2C.config
        echo "::set-output name=status::success"

    - name: Compile the firmware Pi4_Model_B
      id: compile_Pi4_Model_B
      if: steps.UpdateSource.outputs.status == 'success' && !cancelled()
      run: |
        cd /home/$USER/OpenWrtAction
        bash wsl2op.sh Pi4_Model_B.config
        echo "::set-output name=status::success"
        
