#
# Copyright (c) 2022-2023 SMALLPROGRAM <https://github.com/smallprogram/OpenWrtAction>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/smallprogram/OpenWrtAction
# Description: Build OpenWrt using GitHub Actions
#

name: TEST

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
      is_display_detailed:
        description: 'Whether to display detailed information about compilation'
        required: false
        default: 'true'
      is_single_threaded:
        description: 'Whether single-threaded compilation'
        required: false
        default: 'false'
  # schedule:
  #   - cron: 0 */8 * * *

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds_config/custom.feeds.conf.default
  DIY_P1_SH: diy_script/diy-part1.sh
  DIY_P2_SH: diy_script/diy-part2.sh
  COMMIT_LOG_NUM: 1
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_ARTIFACT: false
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
  


jobs:
  job_1:
    runs-on: ubuntu-latest

    steps:
    - name: gen file
      run: |
        dd if=/dev/zero of=myfile.txt bs=1M count=10

    - name: upload
      uses: actions/upload-artifact@v3
      if: steps.tag.outputs.status == 'success'
      with:
        name: myfile
        path: myfile.txt
        retention-days: 5


  job_2:
    needs: job_1
    runs-on: ubuntu-latest

    steps:
    - name: download1
      uses: actions/download-artifact@v3
      if: steps.tag.outputs.status == 'success'
      with:
        name: myfile1


    - name: ls1
      run: |
        ls

    - name: download2
      uses: actions/download-artifact@v3
      if: steps.tag.outputs.status == 'success'
      with:
        name: myfile

    - name: ls2
      run: |
        ls
       


        