#
# Copyright (c) 2022-2023 SMALLPROGRAM <https://github.com/smallprogram/OpenWrtAction>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/smallprogram/OpenWrtAction
# Description: Build OpenWrt using GitHub Actions
#

name: TEST

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  # schedule:
  #   - cron: 0 */8 * * *



jobs:
  job_init: 
    runs-on: ubuntu-latest
    steps:
    - name: Remove old Releases
      uses: smallprogram/delete-older-releases@master
      with:
        keep_latest: 10
        keep_min_download_counts: 7
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate Toolchain Image
      id: generate_image
      run: |

        mkdir output

        cd $GITHUB_WORKSPACE/output
        dd if=/dev/zero of=outputfile.img.00 bs=1M count=1900
        dd if=/dev/zero of=outputfile.img.01 bs=1M count=1900
        dd if=/dev/zero of=outputfile.img.02 bs=1M count=1900
        dd if=/dev/zero of=outputfile.img.03 bs=1M count=1900
        dd if=/dev/zero of=outputfile.img.04 bs=1M count=1900
        dd if=/dev/zero of=outputfile.img.05 bs=1M count=1900
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV

        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload Toolchain to release
      uses: softprops/action-gh-release@v0.1.15
      if: steps.generate_image.outputs.status == 'success'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 'test'
        files: ${{ env.FIRMWARE }}/*    

 