#
# Copyright (c) 2022-2023 SMALLPROGRAM <https://github.com/smallprogram/OpenWrtAction>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/smallprogram/OpenWrtAction
# Description: Build OpenWrt using GitHub Actions
#

name: test

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
      is_display_detailed:
        description: 'Whether to display detailed information about compilation'
        required: false
        default: 'false'
      is_single_threaded:
        description: 'Whether single-threaded compilation'
        required: false
        default: 'false'

jobs:
  job_build:
    runs-on: ubuntu-latest
    name: Build-${{ matrix.platforms }}
    strategy:
      matrix:
        platforms: [a, b, c]

    steps:
    - name: Generate Firmware
      id: compile
      run: |
        is_compile_error=0
        if [ "${{ matrix.platforms }}" = "a" ]; then
          is_compile_error=1
        fi
        if [ "${{ matrix.platforms }}" = "b" ]; then
          is_compile_error=2
        fi
        if [ "${{ matrix.platforms }}" = "c" ]; then
          is_compile_error=3
          exit 1
        fi
        echo "compile result: $is_compile_error"
        echo "is_compile_error=$is_compile_error" >> $GITHUB_OUTPUT
        
  job_organize_tags:
    needs: [job_build]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Organize-Release-Tags

    steps:
    - name: Get Values
      id: organize_tags
      run: |
        a_compile_error="${{ needs.job_build.outputs.compile.is_compile_error }}"
        echo $a_compile_error
        b_compile_error="${{ needs.job_build.outputs.compile.is_compile_error }}"
        echo $b_compile_error
        c_compile_error="${{ needs.job_build.outputs.compile.is_compile_error }}"
        echo $c_compile_error




        