#
# Copyright (c) 2022-2023 SMALLPROGRAM <https://github.com/smallprogram/OpenWrtAction>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/smallprogram/OpenWrtAction
# Description: Build OpenWrt using GitHub Actions
#

name: test

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
      is_display_detailed:
        description: 'Whether to display detailed information about compilation'
        required: false
        default: 'false'
      is_single_threaded:
        description: 'Whether single-threaded compilation'
        required: false
        default: 'false'

jobs:
  job_build:
    runs-on: ubuntu-latest
    name: Build-OpenWrt-${{ matrix.platforms }}
    strategy:
      matrix:
        platforms: [a, b, c]

    steps:
    - name: Generate Firmware
      id: compile
      run: |
        is_compile_error=0
        if [ "${{ matrix.platforms }}" = "a" ]; then
          is_compile_error=1
        fi
        if [ "${{ matrix.platforms }}" = "b" ]; then
          is_compile_error=2
        fi
        if [ "${{ matrix.platforms }}" = "c" ]; then
          is_compile_error=3
          exit 1
        fi
        echo "compile result: $is_compile_error"
        echo "is_compile_error=$is_compile_error" >> $GITHUB_OUTPUT
        
  job_organize_tags:
    needs: [job_build]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Organize-Release-Tags

    steps:
    - name: Get Values
      id: organize_tags
      run: |
        echo "Fetch workflow run jobs"
        curl -H "Authorization: Bearer ${{ github.token }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs" \
          | jq '.jobs[] | select(.name | startswith("Build-OpenWrt-")) | .conclusion'

        json_data=$(curl -s -H "Authorization: Bearer ${{ github.token }}" "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs")
        # name_conclusion_array=($(echo "$json_data" | jq -r '.jobs[] | "\(.name).\(.conclusion)"'))
        name_conclusion_array=($(echo "$json_data" | jq -r '.jobs[] | select(.name | startswith("Build-OpenWrt-")) | "\(.name).\(.conclusion)"'))
        for item in "${name_conclusion_array[@]}"; do
          IFS='.' read -r name conclusion <<< "$item"
          echo "Name: $name"
          echo "Conclusion: $conclusion"
        done




        