#
# Copyright (c) 2022-2023 SMALLPROGRAM <https://github.com/smallprogram/OpenWrtAction>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/smallprogram/OpenWrtAction
# Description: Build OpenWrt using GitHub Actions
#

name: TEST

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  # schedule:
  #   - cron: 0 */8 * * *



jobs:
  job_init: 
    runs-on: ubuntu-latest
    steps:
    - name: Remove old Releases
      uses: smallprogram/delete-older-releases@master
      with:
        keep_latest: 10
        keep_min_download_counts: 7
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate Toolchain Image
      id: generate_image
      run: |

        git clone https://github.com/coolsnowwolf/lede openwrt
        cd openwrt
        git clone https://github.com/coolsnowwolf/lede openwrt1
        git clone https://github.com/coolsnowwolf/lede openwrt2
        cd ..

        du -sh $GITHUB_WORKSPACE

        tar -cf output.tar openwrt/

        ls
        du -sh $GITHUB_WORKSPACE
        
    - name: Upload Firmware Directory
      uses: actions/upload-artifact@v3
      with:
        name: test1
        path: output.tar
        retention-days: 5

  job_init2: 
    runs-on: ubuntu-latest
    needs: job_init
    steps:
    - name: aa
      run: |
        cd $GITHUB_WORKSPACE
        mkdir download

    - name: Download Toolchain Image From Artifacts
      uses: actions/download-artifact@v3
      with:
        name: test1
        path: download

    - name: bbls
      run: |
        cd $GITHUB_WORKSPACE
        tar -xf download/output.tar -C $GITHUB_WORKSPACE
        du -sh $GITHUB_WORKSPACE
        rm -rf download
        du -sh $GITHUB_WORKSPACE
        ls