#
# Copyright (c) 2022-2024 SMALLPROGRAM <https://github.com/smallprogram/OpenWrtAction>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/smallprogram/OpenWrtAction
# Description: Build OpenWrt using GitHub Actions
#

name: testv4

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
      is_display_detailed:
        description: 'Whether to display detailed information about compilation'
        required: false
        default: 'false'
      is_single_threaded:
        description: 'Whether single-threaded compilation'
        required: false
        default: 'false'
  # schedule:
  #   - cron: 0 */8 * * *


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step in job1
        run: echo "Job1 is running"

  job2:
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Step in job2
        run: echo "Job2 is running"
  job22:
    runs-on: ubuntu-latest
    steps:
      - name: Step in job22
        run: exit 1

  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2, job22]
    if: always()
    steps:
      - name: Check job2 status and conditionally execute
        if: ${{ needs.job2.result == 'skipped' }}  # 判断 job2 是否跳过
        run: |
          echo "Job1 ${{ needs.job1.result }}"
          echo "Job2 ${{ needs.job2.result }}"
          echo "Job2 ${{ needs.job22.result }}"