#
# Copyright (c) 2019-2024 smallprogram
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/smallprogram/OpenWrtAction
# File: .github/workflows/Update_Checker.yml
# Description: Source code update checker
#

name: Update_Checker

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  schedule:
    - cron: 0 */8 * * *

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')

    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Get Commit Hash
      id: getHash
      run: |
        git clone https://github.com/coolsnowwolf/lede --filter=blob:none
        cd lede
        echo "SHA_01=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        cd

        git clone https://github.com/coolsnowwolf/packages --filter=blob:none
        cd packages
        echo "SHA_02=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        cd

        git clone https://github.com/coolsnowwolf/luci --filter=blob:none
        cd luci
        echo "SHA_03=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        cd

        git clone https://git.openwrt.org/feed/routing.git
        cd routing
        echo "SHA_04=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        cd
        
        git clone https://git.openwrt.org/feed/telephony.git
        cd telephony
        echo "SHA_05=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        cd

        git clone https://github.com/fw876/helloworld --filter=blob:none
        cd helloworld
        echo "SHA_06=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        cd

        git clone https://github.com/xiaorouji/openwrt-passwall-packages --filter=blob:none
        cd openwrt-passwall-packages
        echo "SHA_07=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        cd

        git clone https://github.com/xiaorouji/openwrt-passwall --filter=blob:none
        cd openwrt-passwall
        echo "SHA_08=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        cd

        git clone https://github.com/xiaorouji/openwrt-passwall2 --filter=blob:none
        cd openwrt-passwall2
        echo "SHA_09=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        cd

        git clone  https://github.com/vernesong/OpenClash.git --filter=blob:none
        cd OpenClash
        echo "SHA_10=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        cd

        git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git --filter=blob:none
        cd luci-theme-argon
        echo "SHA_11=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        cd

        git clone -b 18.06 https://github.com/jerrykuku/luci-app-argon-config.git --filter=blob:none
        cd luci-app-argon-config
        echo "SHA_12=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        cd

        git clone https://github.com/rufengsuixing/luci-app-adguardhome.git --filter=blob:none
        cd luci-app-adguardhome
        echo "SHA_13=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        cd

        git clone https://github.com/sbwml/luci-app-mosdns -b v5 --filter=blob:none
        cd luci-app-mosdns
        echo "SHA_14=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        cd



    - name: Show Commit Head and Combination Heads
      id: combHeader
      run: |
        echo "commitHash_All=\
          ${{steps.getHash.outputs.SHA_01}}\
          ${{steps.getHash.outputs.SHA_02}}\
          ${{steps.getHash.outputs.SHA_03}}\
          ${{steps.getHash.outputs.SHA_04}}\
          ${{steps.getHash.outputs.SHA_05}}\
          ${{steps.getHash.outputs.SHA_06}}\
          ${{steps.getHash.outputs.SHA_07}}\
          ${{steps.getHash.outputs.SHA_08}}\
          ${{steps.getHash.outputs.SHA_09}}\
          ${{steps.getHash.outputs.SHA_10}}\
          ${{steps.getHash.outputs.SHA_11}}\
          ${{steps.getHash.outputs.SHA_12}}\
          ${{steps.getHash.outputs.SHA_13}}\
          ${{steps.getHash.outputs.SHA_14}}" >> $GITHUB_OUTPUT

    - name: Compare Commit Hash
      id: cacheHash
      uses: actions/cache@v3.0.11
      with:
        path: .commitHash_All
        key: HEAD-${{ steps.combHeader.outputs.commitHash_All }}
   

    - name: Save New Commit Hash
      if: steps.cacheHash.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.combHeader.outputs.commitHash_All }} | tee .commitHash_All
        
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 3

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.3.2
      with:
        keep_latest: 5
        keep_min_download_counts: 2
        delete_expired_data: 50
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Trigger build
      if: steps.cacheHash.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: OpenWrt Related Code Updates

